<?php

namespace app\admin\controller;

use app\common\model\ArcTag;
use think\Controller;

class Article extends Controller
{
    protected function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->db = new \app\common\model\Article();
    }

    /**
     * 首页
     * @return mixed
     */
    public function index()
    {
        $filed = $this->db->getAll();
        $this->assign('field', $filed);
        return $this->fetch();
    }

    /**
     * 添加
     * @return mixed
     * @throws \think\db\exception\DataNotFoundException
     * @throws \think\db\exception\ModelNotFoundException
     * @throws \think\exception\DbException
     */
    public function store()
    {
        if (request()->isPost()) {

            $res = $this->db->store(input('post.'));
//            halt($res);
            if (!isset($res['tag'])) {
                return $this->error('请选择文章标签');
            }
            $validate = new \app\admin\validate\Article();

            if (!$validate->check($res)) {
                $this->error($validate->getError());
                exit;
            } else {
                $arc = new \app\common\model\Article([
                    'arc_title' => $res['arc_title'],
                    'arc_author' => $res['arc_author'],
                    'arc_sort' => $res['arc_sort'],
                    'cate_id' => $res['cate_id'],
                    'arc_content' => $res['arc_content'],
                ]);
                $arc->allowField(true)->save();
                foreach ($res['tag'] as $v) {
                    $arctag = new ArcTag([
                        'arc_id' => $arc->arc_id,
                        'tag_id' => $v
                    ]);
                    $arctag->save();
                }
//                echo $arc->arc_id;
//                exit;
                $this->success('添加成功', 'index');
            }
        }
        //获取分类数据
        $cateData = (new \app\common\model\Category())->getAll();
        $this->assign('cateData', $cateData);

        //获取标签数据
        $tagData = db('tag')->select();
        $this->assign('tagData', $tagData);
        return $this->fetch();
    }

    public function changSort()
    {
//        halt($_POST);
        if (request()->isAjax()) {
            $res = $this->db->changeSort(input('post.'));
            $arc = new \app\common\model\Article();
            $arc->save([
                'arc_sort' => $res['arc_sort'],
            ], ['arc_id' => $res['arc_id']]);
        }
    }

    //编辑
    public function edit()
    {
        if (request()->isPost()) {
            $res = $this->db->edit(input('post.'));
            $validate = new \app\admin\validate\Article();
//            halt($res);
            if (!$validate->check($res)) {
//            return ['valid' => 0, 'msg' => $this->getError()];
                $this->error($validate->getError());
                exit;
            } else {
                $arc = new \app\common\model\Article();
                $arc->save([
                    'arc_title' => $res['arc_title'],
                    'arc_author' => $res['arc_author'],
                    'arc_sort' => $res['arc_sort'],
                    'cate_id' => $res['cate_id'],
                    'arc_content' => $res['arc_content'],
                    'arc_id' => $res['arc_id'],
                ], ['arc_id' => $res['arc_id']]);
                $arc->allowField(true)->save();
//                User::where('id','>',10)->delete();
                ArcTag::where('arc_id', '=', $res['arc_id'])->delete();
//                halt($res);
//                halt($res['tag']);
                foreach ($res['tag'] as $v) {
                    $arctag = new ArcTag([
                        'arc_id' => $arc->arc_id,
                        'tag_id' => $v
                    ]);
                    $arctag->save();
                }
                $this->success('修改成功', 'index');
            }


        }
        $arc_id = input('param.arc_id');
        //获取分类数据
        $cateData = (new \app\common\model\Category())->getAll();
        $this->assign('cateData', $cateData);

        //获取标签数据
        $tagData = db('tag')->select();
        $this->assign('tagData', $tagData);

        //获取旧数据
        $oldData = db('article')->find($arc_id);
        $this->assign('oldData', $oldData);
//        halt($oldData);

        //获取标签
        $tag_ids = db('arc_tag')->where('arc_id', $arc_id)->column('tag_id');
        $this->assign('tag_ids', $tag_ids);
        return $this->fetch();
    }


}
