<?php

namespace app\admin\controller;

use think\Controller;

class Link extends Controller
{
    protected $db;

    protected function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->db = new \app\common\model\Link();
    }

    /**
     * 首页
     * @return mixed
     * @throws \think\exception\DbException
     */
    public function index()
    {
        $field = db('link')->paginate(5);
        $this->assign('field', $field);
        return $this->fetch();
    }

    /**
     * 添加友链
     * @return mixed
     */
    public function store()
    {
        if (request()->isPost()) {
            $res = $this->db->store(input('post.'));
            $validate = new \app\admin\validate\Link;
            if (!$validate->check($res)) {
                $this->error($validate->getError());
                exit;
            } else {
                $Link = new \app\common\model\Link([
                    'link_name' => $res['link_name'],
                    'link_url' => $res['link_url'],
                    'link_sort' => $res['link_sort'],
                ]);
                $Link->save();
                $this->success('添加成功', 'index');
            }
        }
        return $this->fetch();
    }

    /**
     * 编辑友链
     * @return mixed
     */
    public function edit()
    {
        if (request()->isPost()) {
            $validate = new \app\admin\validate\Link;
            $res = $this->db->edit(input('post.'));
            if (!$validate->check($res)) {
                $this->error($validate->getError());
                exit;
            } else {
                $cate = new \app\common\model\Link();
                $cate->save([
                    'link_name' => $res['link_name'],
                    'link_url' => $res['link_url'],
                    'link_sort' => $res['link_sort']],
                    ['link_id' => $res['link_id']]);
                $this->success('修改成功', 'index');
            }
        }
        $link_id = input('param.link_id');
        $oldData = $this->db->find($link_id);
        $this->assign('oldData', $oldData);
        return $this->fetch();
    }

    /**
     *删除友链
     */
    public function del()
    {
        $link_id = input('get.link_id');
        if (\app\common\model\Link::destroy($link_id)) {
            $this->success('删除成功', 'index');
            exit;
        } else {
            $this->error('删除失败');
            die;
        }
    }
}
